import type { BreadcrumbList, WebApplication } from "schema-dts"
import { getLocale, locales } from "@/paraglide/runtime.js"
import { m } from "@/paraglide/messages.js"
import { BASE_URL } from "./site-config"

const KEYWORDS = [
  "NAT type",
  "network",
  "WebRTC",
  "STUN",
  "gaming",
  "P2P",
  "connectivity",
  "NAT detection",
  "network analysis",
  "firewall",
  "router",
  "port forwarding",
  "online gaming",
  "video call",
  "remote access",
]

const OG_LOCALE: Record<string, string> = {
  en: "en_US",
  zh: "zh_CN",
  de: "de_DE",
  es: "es_ES",
  fr: "fr_FR",
}

interface PageSeoInput {
  /** Localized URL path of the page, e.g. "/en" or "/zh/nat-types". */
  path: string
  /** Page title; defaults to the app title. Sub-pages get the app title appended. */
  title?: string
  /** Meta / social description; defaults to the app description. */
  description?: string
}

/**
 * Per-page <head> content: title/description/keywords, canonical, hreflang
 * alternates (plus x-default pointing at the browser-language redirector on
 * "/"), Open Graph / Twitter cards and JSON-LD structured data.
 */
export function buildPageHead({ path, title, description }: PageSeoInput) {
  const locale = getLocale()
  const localizedBasePath = `/${locale}`
  const suffix = path.slice(localizedBasePath.length) // "" | "/nat-types"
  const appTitle = m.uiStrings_appTitle()
  const pageTitle = title ? `${title} · ${appTitle}` : appTitle
  const pageDescription = description ?? m.uiStrings_appDescription()
  const url = `${BASE_URL}${path}`
  // Generated by scripts/generate-og.mjs: /og/<locale>[-<page>].png
  const ogImage = `${BASE_URL}/og/${locale}${suffix.replace("/", "-")}.png`

  const webApplicationSchema: WebApplication = {
    "@type": "WebApplication",
    name: appTitle,
    description: m.uiStrings_appDescription(),
    url: `${BASE_URL}${localizedBasePath}`,
    inLanguage: locale,
    applicationCategory: "UtilitiesApplication",
    operatingSystem: "Web Browser",
    browserRequirements: "Requires JavaScript and WebRTC support",
    isAccessibleForFree: true,
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    screenshot: ogImage,
  }

  const breadcrumbSchema: BreadcrumbList = {
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: appTitle,
        item: `${BASE_URL}${localizedBasePath}`,
      },
      ...(title
        ? [
            {
              "@type": "ListItem" as const,
              position: 2,
              name: title,
              item: url,
            },
          ]
        : []),
    ],
  }

  return {
    meta: [
      { title: pageTitle },
      { name: "description", content: pageDescription },
      { name: "keywords", content: KEYWORDS.join(", ") },
      { name: "author", content: appTitle },
      { name: "application-name", content: appTitle },
      {
        name: "robots",
        content: "index, follow, max-image-preview:large, max-snippet:-1",
      },
      { property: "og:type", content: "website" },
      { property: "og:site_name", content: appTitle },
      { property: "og:locale", content: OG_LOCALE[locale] ?? locale },
      { property: "og:title", content: pageTitle },
      { property: "og:description", content: pageDescription },
      { property: "og:url", content: url },
      { property: "og:image", content: ogImage },
      { property: "og:image:type", content: "image/png" },
      { property: "og:image:width", content: "1200" },
      { property: "og:image:height", content: "630" },
      { property: "og:image:alt", content: pageTitle },
      { name: "twitter:card", content: "summary_large_image" },
      { name: "twitter:title", content: pageTitle },
      { name: "twitter:description", content: pageDescription },
      { name: "twitter:image", content: ogImage },
      { name: "twitter:image:alt", content: pageTitle },
    ],
    links: [
      { rel: "canonical", href: url },
      ...locales.map((l) => ({
        rel: "alternate",
        hrefLang: l,
        href: `${BASE_URL}/${l}${suffix}`,
      })),
      { rel: "alternate", hrefLang: "x-default", href: BASE_URL },
    ],
    scripts: [webApplicationSchema, breadcrumbSchema].map((schema) => ({
      type: "application/ld+json",
      children: JSON.stringify({
        "@context": "https://schema.org",
        ...schema,
      }),
    })),
  }
}
